### ISSUE TITLE
这个博客开源了

### ISSUE THREAD

**Issue by yihong0618** [yihong0618/gitblog#177]
因为一篇去年非常触动我的文章--[People Die, but Long Live GitHub](https://laike9m.com/blog/people-die-but-long-live-github,122/)
我决定不再用纸币写日记，进而全部转到GitHub上。如果你看到这个，这个其实不是那些大牛的技术博客，而是单纯的碎碎念偶尔认真的记录自己而已。

---
虽然如此但也经历了几个阶段

1. 纯粹的写issue
2. 写完issue后添加目录到README
3. 改成webhook用flask部署个callback 每次写完issue自动生成新的README
4.  最近算是学会了一些GitHub Action，现在只需要写issue打label就好了，其余完全不用管核心代码再main.py

---

如果你也想自己写issue博客，并自动生成README，你可以参考如下步骤

1. fork this repo (or just copy the  file whatever)
2. change all the things in [action](https://github.com/yihong0618/gitblog/blob/master/.github/workflows/generate_readme.yml) to yours
3. change `ME_GITHUB_NAME ` in main.py to yours 
4. just  write issue and add label

**Comment by yihong0618** [comment]
2020.08.24更新: 增加了显示更多。 完善了置顶功能，现在只需要打label就可以了。

**Comment by yihong0618** [comment]
现在不用改任何东西在main.py了只需要更改自己的token就可以了，增加了todo标签

**Comment by yihong0618** [comment]
完善了todo标签，优化了一点点代码。

**Comment by Aaronwn** [comment]
你好，有自己的blog,直接copy你的main.py可以吗

**Comment by yihong0618** [comment]
> 你好，有自己的blog,直接copy你的main.py可以吗

当然可以啊。但是你还得把 .github那个文件夹拷贝过去。那个是action用的，还得生成自己的github secret token 我这里叫G_T你可以改成你自己的名字，如果有问题随时问我可以。之后你就可以写issue 打label就行。

**Comment by yihong0618** [comment]
把 todo list 放在下面了， 如果想放在最上可以修改 write md 的函数顺序

**Comment by yihong0618** [comment]
增加了一些教程。

**Comment by yihong0618** [comment]
支持了[kb](https://github.com/gnebbia/kb)
现在只需要打kb标签，在issue里评论就能把记录整合进kb中。
see https://github.com/yihong0618/gitblog/issues/189

**Comment by yihong0618** [comment]
![image](https://user-images.githubusercontent.com/15976103/96670577-3dec9580-1392-11eb-9915-cce19954cd6a.png)

**Comment by yihong0618** [comment]
![image](https://user-images.githubusercontent.com/15976103/96670695-958b0100-1392-11eb-8b10-009f3321f743.png)

![image](https://user-images.githubusercontent.com/15976103/96670714-a471b380-1392-11eb-8442-7465c87f8cd4.png)

![image](https://user-images.githubusercontent.com/15976103/96671101-abe58c80-1393-11eb-85f6-f97309d69809.png)

**Comment by superleeyom** [comment]
cool，之前也想把文章整合进readme中，看到[这篇文章](https://github.com/jwenjian/ghiblog/issues/1)，发现了你再底下的留言，真是太巧了吧，他这个感觉就太花哨了，你这个挺符合我的要求的，拷贝你的这些workflows yml等文件后，完美使用，只是这个`generate_readme.yml` 里的：
```
      - name: Push README
        uses: github-actions-x/commit@v2.6
        with:
          github-token: ${{ secrets.G_T }}
          commit-message: "Refresh README"
          files: README.md
          rebase: 'true'
          name: superleeyom 
          email: 635709492@qq.com
```
一定要改成自己的 name 和 email，否则就会以当前 name 的用户更新 README.md，我拷贝过来后忘记改了，然后恭喜 @yihong0618 成为我 [blog](https://github.com/superleeyom/blog) 仓库的 contributor，哈哈，记得改过来就行
