### ISSUE TITLE
CSS存档

### ISSUE THREAD

**Issue by yihong0618** [yihong0618/gitblog#21]
1. .xxx>li。>是子代选择符，它表示的是选择.xxx的子代li
2. @media 如果文档宽度小于 300 像素则修改背景颜色(background-color):
```css
 @media screen and (max-width: 300px) {
    body {
        background-color:lightblue;
    }
}
```
